version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: restaurant_db0-
    environment:
      POSTGRES_DB: MesaFacil
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always



